### ISSUE TITLE
US5: Write application errors to a log file

### ISSUE THREAD

**Issue by BorislavZlatanov** [linguisticteam/resource-central#30]
Related user story:
US5: As a developer, I can see a log file which has all the errors related to the system's operation (not errors related to data validation), so that I can be aware of problems and more easily debug them.

Description:
We have errors that are raised because the user supplied incorrect data. Those errors do not need to be logged to a file, as they are not relevant to the developer but only to the user. We also have errors that are raised when some part of the application does not complete its operation successfully. For example, if a stored procedure did not complete successfully, we raise an error. These kinds of errors need to be logged to a file so that developers can see existing problems and track them down.

**Comment by oxygenbarker** [comment]
Created Logger class with basic logging functions.

**Comment by oxygenbarker** [comment]
The instantiation of the Error class was replaced by a call to a static initialization function. https://github.com/linguisticteam/resource-central/commit/b1c85d10a6c5d32b2daaec801a9ed5b52c4938b6

**Comment by oxygenbarker** [comment]
Removed printing responsibility from ErrorTemplate class. https://github.com/linguisticteam/resource-central/commit/03d4013797de9a38b9d23cc88a48d6a768575877

**Comment by BorislavZlatanov** [comment]
This is now done.
